---
title: "Spawning stock biomass-per-recruit (SBPR)"
output: pdf_document
date: "`r format(Sys.time(), '%d %B, %Y')`"
---

```{r echo=FALSE}
plot(sbprExec$results$F_vs_SPR[,2]~sbprExec$results$F_vs_SPR[,1],ylab="SPR",xlab="Fishing Mortality",type="l")
abline(h=sbprExec$results$Reference_Point[1,2], col = "red", lty = 2)
legend(1.4, 8, legend=c("SSB_per_recruit"),col=c("red"), lty=2, cex=0.8)
```

```{r echo=FALSE}
plot(sbprExec$results$F_vs_SPR[,3]~sbprExec$results$F_vs_SPR[,1],ylab="% Max SPR",xlab="Fishing Mortality",type="l")
abline(h=sbprExec$perc, v = sbprExec$results$Reference_Point[1,1], col = "red", lty = 2)
leg <- paste0(sbprExec$perc, "% MSP")
legend(1.5, 85, legend=c(leg),col=c("red"), lty=2, cex=0.8)
```
\pagebreak

## Reference Points - F at 30%MSP
```{r echo=FALSE, results='asis'}
#df <- as.data.frame(sbprExec$results$Reference_Point)
df <- data.frame(F=sbprExec$results$Reference_Point[1], SSB_Per_Recruit=sbprExec$results$Reference_Point[2])
colnames(df) <- c("F", "SSB_Per_Recruit")
knitr::kable(df, digits = 2, align=rep('c', 5))
```
  
******
## Input parameters  
Input File: `r input$fileSbpr$name`  

M: `r input$SBPR_M`  
pF: `r input$SBPR_pF`  
pM: `r input$SBPR_pM`  
MSP: `r input$SBPR_MSP`  
maxF: `r input$SBPR_maxF`  
incrF: `r input$SBPR_incrF`  
